---
title: "Preprints"
author: "Matthias Mittner"
date: "today"
---

```{r setup, cache=F, include=FALSE}
library(tidyverse)
library(lubridate)
library(glue)
library(bib2df)
library(fs)
library(DT)
source("../lib/functions.R")
```

```{r, cache=F, include=FALSE}
## preprints from psyarxiv.bib
bib2df("../../org/cv/data/bib/psyarxiv.bib", separate_names = T) |>
  select(authors=AUTHOR, pages=PAGES, title=TITLE, year=YEAR,
         link=URL, vol=VOLUME, num=NUMBER, month=MONTH, date=DATE) %>%
  extract(date, c("year","month","day"), regex = "([0-9]+)-?([0-9]?[0-9]?)-?([0-9]?[0-9]?)") %>%
  mutate(year=as.integer(year), month=as.integer(month)) %>%
  mutate(title=strip_curly_braces(title),
         date=ymd(sprintf("%s-%s-%s",year,month,day)),
         status="submitted", unpublished=T, citation="",
         authors=map(authors, ~.x %>%
                       rename(family_name=last_name,given_name=first_name) %>%
                       mutate(family_name=strip_curly_braces(family_name),
                              given_name=strip_curly_braces(given_name))
                       )) -> preprints

# other preprints not on psyarxiv
if(fs::is_file("../../org/cv/data/bib/preprints.bib") & dim(bib2df("../../org/cv/data/bib/preprints.bib"))[1]>0){
  bib2df("../../org/cv/data/bib/preprints.bib", separate_names = T) %>%
    select(authors=AUTHOR, pages=PAGES, title=TITLE, year=YEAR,
           doi=DOI, link=URL, vol=VOLUME, num=NUMBER, month=MONTH, date=DATE) %>%
    extract(date, c("year","month","day"), regex = "([0-9]+)-?([0-9]?[0-9]?)-?([0-9]?[0-9]?)") %>%
    mutate(year=as.integer(year), month=as.integer(month)) %>%
    mutate(title=strip_curly_braces(title),
           date=ymd(sprintf("%s-%s-%s",year,month,day)),
           status="submitted", unpublished=T, citation="",
           authors=map(authors, ~.x %>%
                         rename(family_name=last_name,given_name=first_name) %>%
                         mutate(family_name=strip_curly_braces(family_name),
                                given_name=strip_curly_braces(given_name))
                         )) -> preprints.add
  full_join(preprints, preprints.add) -> preprints
}

# Build citation strings
for(i in 1:dim(preprints)[1]){
  authors=preprints[i,]$authors[[1]]
  if(dim(authors)[1]==1){
    latexauth<-glue_data(authors, "**{family_name}, {str_sub(given_name, 1,1)}.**")
  } else {
    latexauth<-glue_data(authors, "{family_name}, {str_sub(given_name, 1,1)}.")
    latexauth=if_else(startsWith(latexauth, "Mittner") | startsWith(latexauth, "Ihrke"), sprintf("**%s**",latexauth), as.character(latexauth))
    latexauth<-glue_collapse(latexauth, sep = ", ", last = " & ")
  }
  ref=with(preprints[i,], glue("{latexauth} ({date}). {title}. {link} status: {status}"))
  preprints$citation[i]=ref
}

preprints %>% arrange(desc(date)) %>% ungroup -> preprints
```


This is a list of all preprints published by my group, so far. The preprints for which the status is "published" all have a corresponding publication on my [publication list](/publications.qmd).

```{r, echo=F, results='asis'}
#| column: screen-inset-shaded
#| 
mdtohtml <- function(x){
  purrr::map_chr(x, function(y){
    markdown::markdownToHTML(text=y, fragment.only = T)
  })
}

#knitr::kable(preprints %>% select(date,citation, link, status))
d <- preprints %>% select(date,citation, link, status) %>% 
  mutate(link=mdtohtml(link),
         citation=mdtohtml(citation))
DT::datatable(d, escape = F)
```